version: '3'
services:
  db:
    build: .
    container_name: crud_farm_app
    restart: always
    environment:
      POSTGRES_DB: db_farm_app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432